### ISSUE TITLE
In StereoSoundfiler nChan widget is not visible

### ISSUE THREAD

**Issue by elmiquito** [BirminghamConservatoire/IntegraLive#1005] opened 2016-01-07 18:18 UTC
Expected behaviour: when a soundfile is loaded a RadioGroup widget should show if the file is mono or stereo.

Actual behaviour: the RadioGroup widget is not visible in the attributes pane of the StereoSoundfiler module

**Comment by NiccoloGranieri** [comment] 2016-01-07 18:24
Did you download the latest build of the StereoSoundfiler? Because the one with the nChan widget is not part of the last released build!

**Comment by elmiquito** [comment] 2016-01-07 18:34
I've cloned the repository today...did I do anything wrong?

**Comment by NiccoloGranieri** [comment] 2016-01-07 18:38
Absolutely not, you did everything as you should have! Then it is strange, because I just checked, and the widget shows up correctly.

Could you please check that the StereoSoundfiler you are using was last modified of Monday 14th of December 2015?

**Comment by elmiquito** [comment] 2016-01-07 18:50
Yes, last modified date is 2015-12-14 12:25:39.981000

**Comment by NiccoloGranieri** [comment] 2016-01-07 19:11
Are you running on Mac OSX? If yes, what version of IL are you running?

**Comment by jamiebullock** [comment] 2016-01-07 20:45
I wasn't aware of this new feature, but it makes me wonder if we should consider having just one Soundfiler which is multichannel, i.e. we make the OctoSoundfiler *the* Soundfiler and deprecate the other Soundfilers.

**Comment by elmiquito** [comment] 2016-01-07 22:13
Mac OSX El Capitan 10.11.1
Integra Live 1.7.1.3310

On 7 Jan 2016, at 19:12, Niccolò <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you running on Mac OSX? If yes, what version of IL are you running?

**Comment by NiccoloGranieri** [comment] 2016-01-07 22:33
@jamiebullock It was assigned to James Dooley, and as I thought it could be fairly easy to do, I did! We could think of implementing it in the OctoSoundfiler.

@elmiquito Very, very strange, it works fine for me! I'll do some digging in it, thanks for pointing it out!

**Comment by elmiquito** [comment] 2016-01-08 08:17
If we implemented the OctoSoundfiler as the only Soundfiler you would have a chunky and only partially used module widget on the canvas in most use cases (playing and/or recording mono and stereo sound files), as changes in the nChan settings would not change the number of input and output pins on the module widget.

**Comment by jamiebullock** [comment] 2016-01-08 09:03
@NiccoloGranieri you mean this is actually a fix for an older issue? Can you link to the issue?

**Comment by jamiebullock** [comment] 2016-01-08 09:12
@elmiquito true, but that leads to the wider issue of how we deal with modules with more than (say) 4 I/O pins. Anything more than that is ugly and wastes space. It's not a topic for this thread, but in the medium term I think we need to figure out how to solve this.

**Comment by NiccoloGranieri** [comment] 2016-01-11 12:17
Hello @elmiquito I can't seem to be able to reproduce the issue either on my machine or the ones in the lab, so could you be so kind to send me the logs so I can see if there is some issue with the GUI loading?

@jamiebullock  the issue I closed was: 'mono' indicator in Stereo Soundfiler #274

**Comment by elmiquito** [comment] 2016-01-11 17:10
Closed #1005, apparently only a commit sync issue in github.

**Closed** 2016-01-11 17:11 UTC
Labels: Module Creator, Modules
